const Path = require('path')
const mkdirp = require('mkdirp')
const fs = require('fs')
const Config = require('ssb-config/inject')
const ssbKeys = require('ssb-keys')

const startSsbServer = (plugins, opts, ssbPath) => new Promise((resolve, reject) => {
  const appName = 'ssb'
  let config = Config(appName, opts)
  config.path = ssbPath
  config.keys = ssbKeys.loadOrCreateSync(Path.join(config.path, 'secret'))
  console.log('Starting SSB SERVER')
  // require('../../../open-app/super-ssb-server')
  const sbot = require('ssb-server')
    .use(require('ssb-server/plugins/onion'))
    .use(require('ssb-server/plugins/unix-socket'))
    .use(require('ssb-server/plugins/no-auth'))
    .use(require('ssb-server/plugins/plugins'))
    .use(require('ssb-server/plugins/master'))
    .use(require('ssb-gossip'))
    .use(require('ssb-replicate'))
    .use(require('ssb-friends'))
    .use(require('ssb-blobs'))
    .use(require('ssb-invite'))
    // .use(require('community-apps-ssb-plugin'))
    .use(require('ssb-server/plugins/local'))
    .use(require('ssb-server/plugins/logging'))
    .use(require('ssb-query'))
    .use(require('ssb-ws'))
    .use(require('ssb-ebt'))
    .use(require('ssb-ooo'))
    // add third-party plugins
    // require('ssb-server/plugins/plugins').loadUserPlugins(createSsbServer, config)
    // .use(require('ssb-serve-blobs'))
    // .use(require('ssb-backlinks'))
    // .use(require('ssb-private'))
    // .use(require('ssb-about'))
    // .use(require('ssb-contacts'))
    // .use(require('ssb-threads'))
    .call(null, config)
  const manifest = sbot.getManifest()
  fs.writeFileSync(Path.join(config.path, 'manifest.json'), JSON.stringify(manifest))
  resolve(sbot)
})
  
module.exports = (plugins, opts, paths) => {
  const { ssbPath } = paths
  return startSsbServer(plugins, opts, ssbPath)
    .then((sbot) => sbot)
}